services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - wanderlust-net

  redis-container:
    image: redis:latest
    container_name: redis-container
    restart: unless-stopped
    networks:
      - wanderlust-net

  backend-container:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-container
    restart: unless-stopped
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis-container
    networks:
      - wanderlust-net

  frontend-container:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-container
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend-container
    networks:
      - wanderlust-net

networks:
  wanderlust-net:
    external: true

volumes:
  mongo-data:
